path test.fiz.sample

import {
    java.io.File
    test.fiz.sample.FileUtil
}

type MakeFile {
  main {
    File f= File("test.txt")
    println(f)
    f.createNewFile()
    println(FileUtil.writeOut(f, "Testing this out!"))
  }

}
