path test.fiz.sample

use java.io.File
use test.fiz.sample.FileUtil

type MakeFile {
  main {
    File f: File("test.txt")
    println(f)
    f.createNewFile()
    println(FileUtil.writeOut(f, "Testing this out!"))
  }

}
