# This workflow will test this Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test with Maven

on:
  workflow_dispatch:
  push:

jobs:
  test:
    # linux is cool. Maybe I'll add more targets later? shouldn't ever matter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          # this distribution is cached by github actions
          distribution: 'temurin'
          # jdk version to use, specified in pom.xml
          java-version: '21'
          # use the github actions cached jdk if available.
          check-latest: false
      - name: mvn test
        # maven almost always fails to generate sources correctly without cleaning
        # transfer progress is disabled to avoid spamming the log with progress bars
        run: mvn clean test --file pom.xml --no-transfer-progress
