# This workflow will test this Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test with Maven

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Java 19
        uses: actions/setup-java@v1
        with:
          java-version: 19
      - name: mvn test
        run: mvn clean test --file bootstrap/pom.xml --no-transfer-progress
